name: 'Set imagePullSecrets field in input manifest files'
description: 'Takes a docker-registry secret that has already been set up and in cluster and adds these secrets to the imagePullSecrets field'
inputs:
   # Please ensure you have used either azure/k8s-actions/aks-set-context or azure/k8s-actions/k8s-set-context in the workflow before this action
   # You also need to have kubectl installed (azure/setup-kubectl)
   namespace:
      description: 'Choose the target Kubernetes namespace. If the namespace is not provided, the commands will run in the default namespace.'
      required: false
   manifests:
      description: 'Path to the manifest files which will be used for deployment.'
      required: true
   images:
      description: 'Fully qualified resource URL of the image(s) to be used for substitutions on the manifest files Example: contosodemo.azurecr.io/helloworld:test'
      required: false
   imagepullsecrets:
      description: 'Name of a docker-registry secret that has already been set up within the cluster. Each of these secret names are added under imagePullSecrets field for the workloads found in the input manifest files'
      required: false
   pull-images:
      description: "Switch whether to pull the images from the registry before deployment to find out Dockerfile's path in order to add it to the annotations"
      required: false
      default: true
   resource-group:
      description: 'Name of resource group - Only required if using private cluster'
      required: false
   name:
      description: 'Resource group name - Only required if using private cluster'
      required: false

branding:
   color: 'green'
runs:
   using: 'node16'
   main: 'lib/index.js'
